name: Deploy Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Deploy
        run: sudo mvn clean install

      - name: Complete
        run: sudo java -jar /home/actions-runner/_work/bake_boss_backend/target/bake_boss_backend-0.0.1-SNAPSHOT.jar &
